import { toRomaji } from 'wanakana'

export type SeedEnglishWord = {
  word: string
  meaningZh: string
  tags: string[]
}

export type SeedJapaneseSentence = {
  sentence: string
  romaji: string
  meaningZh: string
  vocabulary: ReadonlyArray<{ word: string; meaningZh: string }>
  tags: string[]
}

const ENGLISH_SEED_BASE: SeedEnglishWord[] = [
  { word: 'abandon', meaningZh: '放棄', tags: ['general', 'verb'] },
  { word: 'ability', meaningZh: '能力', tags: ['general', 'noun'] },
  { word: 'abroad', meaningZh: '在國外', tags: ['travel', 'adverb'] },
  { word: 'accept', meaningZh: '接受', tags: ['general', 'verb'] },
  { word: 'accomplish', meaningZh: '完成', tags: ['work', 'verb'] },
  { word: 'accurate', meaningZh: '精確的', tags: ['study', 'adjective'] },
  { word: 'achieve', meaningZh: '達成', tags: ['work', 'verb'] },
  { word: 'adapt', meaningZh: '適應', tags: ['general', 'verb'] },
  { word: 'addition', meaningZh: '增加', tags: ['study', 'noun'] },
  { word: 'adjust', meaningZh: '調整', tags: ['general', 'verb'] },
  { word: 'admire', meaningZh: '欣賞', tags: ['general', 'verb'] },
  { word: 'advance', meaningZh: '進步；推進', tags: ['work', 'verb'] },
  { word: 'advice', meaningZh: '建議', tags: ['general', 'noun'] },
  { word: 'affect', meaningZh: '影響', tags: ['general', 'verb'] },
  { word: 'afford', meaningZh: '負擔得起', tags: ['life', 'verb'] },
  { word: 'agency', meaningZh: '機構', tags: ['business', 'noun'] },
  { word: 'agenda', meaningZh: '議程', tags: ['business', 'noun'] },
  { word: 'aggressive', meaningZh: '積極進取的', tags: ['work', 'adjective'] },
  { word: 'analyze', meaningZh: '分析', tags: ['study', 'verb'] },
  { word: 'announce', meaningZh: '宣布', tags: ['business', 'verb'] },
  { word: 'annual', meaningZh: '每年的', tags: ['business', 'adjective'] },
  { word: 'anxious', meaningZh: '焦慮的', tags: ['emotion', 'adjective'] },
  { word: 'apology', meaningZh: '道歉', tags: ['general', 'noun'] },
  { word: 'appoint', meaningZh: '任命；指定', tags: ['business', 'verb'] },
  { word: 'appreciate', meaningZh: '感謝；欣賞', tags: ['general', 'verb'] },
  { word: 'approach', meaningZh: '方法；接近', tags: ['study', 'noun'] },
  { word: 'appropriate', meaningZh: '適當的', tags: ['general', 'adjective'] },
  { word: 'arrange', meaningZh: '安排', tags: ['general', 'verb'] },
  { word: 'article', meaningZh: '文章', tags: ['study', 'noun'] },
  { word: 'assist', meaningZh: '協助', tags: ['work', 'verb'] },
  { word: 'assume', meaningZh: '假設', tags: ['study', 'verb'] },
  { word: 'attempt', meaningZh: '嘗試', tags: ['general', 'verb'] },
  { word: 'attend', meaningZh: '參加', tags: ['general', 'verb'] },
  { word: 'attract', meaningZh: '吸引', tags: ['business', 'verb'] },
  { word: 'available', meaningZh: '可取得的', tags: ['general', 'adjective'] },
  { word: 'average', meaningZh: '平均', tags: ['study', 'noun'] },
  { word: 'avoid', meaningZh: '避免', tags: ['general', 'verb'] },
  { word: 'balance', meaningZh: '平衡', tags: ['life', 'noun'] },
  { word: 'benefit', meaningZh: '益處', tags: ['work', 'noun'] },
  { word: 'brief', meaningZh: '簡短的', tags: ['business', 'adjective'] },
  { word: 'budget', meaningZh: '預算', tags: ['business', 'noun'] },
  { word: 'candidate', meaningZh: '候選人', tags: ['business', 'noun'] },
  { word: 'career', meaningZh: '職涯', tags: ['work', 'noun'] },
  { word: 'category', meaningZh: '分類', tags: ['study', 'noun'] },
  { word: 'challenge', meaningZh: '挑戰', tags: ['general', 'noun'] },
  { word: 'clarify', meaningZh: '釐清', tags: ['study', 'verb'] },
  { word: 'collaborate', meaningZh: '合作', tags: ['work', 'verb'] },
  { word: 'comfort', meaningZh: '安慰；舒適', tags: ['emotion', 'noun'] },
  { word: 'commitment', meaningZh: '承諾', tags: ['work', 'noun'] },
  { word: 'communicate', meaningZh: '溝通', tags: ['general', 'verb'] },
  { word: 'compare', meaningZh: '比較', tags: ['study', 'verb'] },
  { word: 'complaint', meaningZh: '抱怨', tags: ['general', 'noun'] },
  { word: 'complex', meaningZh: '複雜的', tags: ['study', 'adjective'] },
  { word: 'conclude', meaningZh: '下結論', tags: ['study', 'verb'] },
  { word: 'confirm', meaningZh: '確認', tags: ['general', 'verb'] },
  { word: 'connect', meaningZh: '連結', tags: ['technology', 'verb'] },
  { word: 'consider', meaningZh: '考慮', tags: ['general', 'verb'] },
  { word: 'consistent', meaningZh: '一致的', tags: ['work', 'adjective'] },
  { word: 'construct', meaningZh: '建構', tags: ['study', 'verb'] },
  { word: 'consume', meaningZh: '消耗', tags: ['life', 'verb'] },
  { word: 'contact', meaningZh: '聯絡', tags: ['general', 'noun'] },
  { word: 'content', meaningZh: '內容', tags: ['study', 'noun'] },
  { word: 'contribute', meaningZh: '貢獻', tags: ['work', 'verb'] },
  { word: 'convenient', meaningZh: '方便的', tags: ['life', 'adjective'] },
  { word: 'conversation', meaningZh: '對話', tags: ['language', 'noun'] },
  { word: 'cooperate', meaningZh: '合作', tags: ['work', 'verb'] },
  { word: 'creative', meaningZh: '有創意的', tags: ['work', 'adjective'] },
  { word: 'critical', meaningZh: '關鍵的；批判的', tags: ['study', 'adjective'] },
  { word: 'culture', meaningZh: '文化', tags: ['general', 'noun'] },
  { word: 'current', meaningZh: '目前的', tags: ['general', 'adjective'] },
  { word: 'deadline', meaningZh: '截止期限', tags: ['work', 'noun'] },
  { word: 'decide', meaningZh: '決定', tags: ['general', 'verb'] },
  { word: 'deliver', meaningZh: '交付', tags: ['work', 'verb'] },
  { word: 'demand', meaningZh: '需求', tags: ['business', 'noun'] },
  { word: 'demonstrate', meaningZh: '展示', tags: ['study', 'verb'] },
  { word: 'depend', meaningZh: '依賴', tags: ['general', 'verb'] },
  { word: 'describe', meaningZh: '描述', tags: ['language', 'verb'] },
  { word: 'design', meaningZh: '設計', tags: ['technology', 'noun'] },
  { word: 'develop', meaningZh: '發展', tags: ['work', 'verb'] },
  { word: 'difficult', meaningZh: '困難的', tags: ['general', 'adjective'] },
  { word: 'discuss', meaningZh: '討論', tags: ['general', 'verb'] },
  { word: 'distance', meaningZh: '距離', tags: ['travel', 'noun'] },
  { word: 'document', meaningZh: '文件', tags: ['work', 'noun'] },
  { word: 'effective', meaningZh: '有效的', tags: ['work', 'adjective'] },
  { word: 'efficient', meaningZh: '高效率的', tags: ['work', 'adjective'] },
  { word: 'encourage', meaningZh: '鼓勵', tags: ['emotion', 'verb'] },
  { word: 'energy', meaningZh: '能量；精力', tags: ['life', 'noun'] },
  { word: 'engineer', meaningZh: '工程師', tags: ['technology', 'noun'] },
  { word: 'enhance', meaningZh: '提升', tags: ['work', 'verb'] },
  { word: 'enroll', meaningZh: '註冊（課程）', tags: ['study', 'verb'] },
  { word: 'environment', meaningZh: '環境', tags: ['general', 'noun'] },
  { word: 'equipment', meaningZh: '設備', tags: ['technology', 'noun'] },
  { word: 'essential', meaningZh: '必要的', tags: ['general', 'adjective'] },
  { word: 'evaluate', meaningZh: '評估', tags: ['study', 'verb'] },
  { word: 'evidence', meaningZh: '證據', tags: ['study', 'noun'] },
  { word: 'exact', meaningZh: '精確的', tags: ['study', 'adjective'] },
  { word: 'expand', meaningZh: '擴展', tags: ['work', 'verb'] },
  { word: 'expect', meaningZh: '期待', tags: ['emotion', 'verb'] },
  { word: 'experience', meaningZh: '經驗', tags: ['general', 'noun'] },
  { word: 'explore', meaningZh: '探索', tags: ['travel', 'verb'] },
  { word: 'express', meaningZh: '表達', tags: ['language', 'verb'] },
  { word: 'feature', meaningZh: '功能；特色', tags: ['technology', 'noun'] },
  { word: 'focus', meaningZh: '專注', tags: ['study', 'noun'] },
  { word: 'forecast', meaningZh: '預測', tags: ['business', 'noun'] },
  { word: 'frequent', meaningZh: '頻繁的', tags: ['general', 'adjective'] },
  { word: 'function', meaningZh: '功能', tags: ['technology', 'noun'] },
  { word: 'generate', meaningZh: '產生', tags: ['technology', 'verb'] },
  { word: 'global', meaningZh: '全球的', tags: ['general', 'adjective'] },
  { word: 'goal', meaningZh: '目標', tags: ['work', 'noun'] },
  { word: 'guidance', meaningZh: '指導', tags: ['study', 'noun'] },
  { word: 'habit', meaningZh: '習慣', tags: ['life', 'noun'] },
  { word: 'highlight', meaningZh: '強調', tags: ['study', 'verb'] },
  { word: 'improve', meaningZh: '改善', tags: ['work', 'verb'] },
  { word: 'include', meaningZh: '包含', tags: ['general', 'verb'] },
  { word: 'increase', meaningZh: '增加', tags: ['business', 'verb'] },
  { word: 'independent', meaningZh: '獨立的', tags: ['life', 'adjective'] },
  { word: 'influence', meaningZh: '影響力', tags: ['general', 'noun'] },
  { word: 'inform', meaningZh: '通知', tags: ['business', 'verb'] },
  { word: 'insight', meaningZh: '洞察', tags: ['study', 'noun'] },
  { word: 'install', meaningZh: '安裝', tags: ['technology', 'verb'] },
  { word: 'instruction', meaningZh: '說明', tags: ['study', 'noun'] },
  { word: 'interest', meaningZh: '興趣', tags: ['emotion', 'noun'] },
  { word: 'interrupt', meaningZh: '打斷', tags: ['language', 'verb'] },
  { word: 'introduce', meaningZh: '介紹', tags: ['language', 'verb'] },
  { word: 'invest', meaningZh: '投資', tags: ['business', 'verb'] },
  { word: 'issue', meaningZh: '議題；問題', tags: ['general', 'noun'] },
  { word: 'journal', meaningZh: '日誌', tags: ['study', 'noun'] },
  { word: 'knowledge', meaningZh: '知識', tags: ['study', 'noun'] },
  { word: 'language', meaningZh: '語言', tags: ['language', 'noun'] },
  { word: 'launch', meaningZh: '推出', tags: ['business', 'verb'] },
  { word: 'leader', meaningZh: '領導者', tags: ['work', 'noun'] },
  { word: 'learn', meaningZh: '學習', tags: ['study', 'verb'] },
  { word: 'lecture', meaningZh: '演講；課程', tags: ['study', 'noun'] },
  { word: 'limit', meaningZh: '限制', tags: ['general', 'noun'] },
  { word: 'local', meaningZh: '在地的', tags: ['travel', 'adjective'] },
  { word: 'maintain', meaningZh: '維持', tags: ['work', 'verb'] },
  { word: 'manage', meaningZh: '管理', tags: ['work', 'verb'] },
  { word: 'manual', meaningZh: '手冊', tags: ['technology', 'noun'] },
  { word: 'market', meaningZh: '市場', tags: ['business', 'noun'] },
  { word: 'measure', meaningZh: '衡量', tags: ['study', 'verb'] },
  { word: 'method', meaningZh: '方法', tags: ['study', 'noun'] },
  { word: 'motivate', meaningZh: '激勵', tags: ['emotion', 'verb'] },
  { word: 'network', meaningZh: '網路；人脈', tags: ['technology', 'noun'] },
  { word: 'observe', meaningZh: '觀察', tags: ['study', 'verb'] },
  { word: 'opinion', meaningZh: '意見', tags: ['language', 'noun'] },
  { word: 'opportunity', meaningZh: '機會', tags: ['work', 'noun'] },
  { word: 'option', meaningZh: '選項', tags: ['general', 'noun'] },
  { word: 'organize', meaningZh: '整理；組織', tags: ['work', 'verb'] },
  { word: 'outcome', meaningZh: '結果', tags: ['study', 'noun'] },
  { word: 'participate', meaningZh: '參與', tags: ['general', 'verb'] },
  { word: 'patient', meaningZh: '有耐心的', tags: ['emotion', 'adjective'] },
  { word: 'perform', meaningZh: '執行；表演', tags: ['work', 'verb'] },
  { word: 'plan', meaningZh: '計畫', tags: ['work', 'noun'] },
  { word: 'platform', meaningZh: '平台', tags: ['technology', 'noun'] },
  { word: 'policy', meaningZh: '政策', tags: ['business', 'noun'] },
  { word: 'practice', meaningZh: '練習', tags: ['language', 'noun'] },
  { word: 'predict', meaningZh: '預測', tags: ['study', 'verb'] },
  { word: 'prepare', meaningZh: '準備', tags: ['general', 'verb'] },
  { word: 'present', meaningZh: '呈現', tags: ['business', 'verb'] },
  { word: 'priority', meaningZh: '優先順序', tags: ['work', 'noun'] },
  { word: 'process', meaningZh: '流程', tags: ['work', 'noun'] },
  { word: 'produce', meaningZh: '生產；產出', tags: ['business', 'verb'] },
  { word: 'progress', meaningZh: '進度', tags: ['study', 'noun'] },
  { word: 'project', meaningZh: '專案', tags: ['work', 'noun'] },
  { word: 'promote', meaningZh: '推廣；升遷', tags: ['business', 'verb'] },
  { word: 'protect', meaningZh: '保護', tags: ['general', 'verb'] },
  { word: 'provide', meaningZh: '提供', tags: ['general', 'verb'] },
  { word: 'publish', meaningZh: '發表', tags: ['study', 'verb'] },
  { word: 'quality', meaningZh: '品質', tags: ['business', 'noun'] },
  { word: 'question', meaningZh: '問題', tags: ['language', 'noun'] },
  { word: 'quickly', meaningZh: '快速地', tags: ['general', 'adverb'] },
  { word: 'recommend', meaningZh: '推薦', tags: ['general', 'verb'] },
  { word: 'record', meaningZh: '紀錄', tags: ['study', 'verb'] },
  { word: 'reduce', meaningZh: '減少', tags: ['business', 'verb'] },
  { word: 'reflect', meaningZh: '反思', tags: ['emotion', 'verb'] },
  { word: 'regular', meaningZh: '規律的', tags: ['life', 'adjective'] },
  { word: 'relax', meaningZh: '放鬆', tags: ['emotion', 'verb'] },
  { word: 'reliable', meaningZh: '可靠的', tags: ['work', 'adjective'] },
  { word: 'replace', meaningZh: '取代', tags: ['general', 'verb'] },
  { word: 'report', meaningZh: '報告', tags: ['business', 'noun'] },
  { word: 'request', meaningZh: '請求', tags: ['general', 'noun'] },
  { word: 'research', meaningZh: '研究', tags: ['study', 'noun'] },
  { word: 'resource', meaningZh: '資源', tags: ['work', 'noun'] },
  { word: 'respond', meaningZh: '回應', tags: ['language', 'verb'] },
  { word: 'result', meaningZh: '結果', tags: ['study', 'noun'] },
  { word: 'review', meaningZh: '複習；檢視', tags: ['study', 'verb'] },
  { word: 'schedule', meaningZh: '行程；排程', tags: ['work', 'noun'] },
  { word: 'section', meaningZh: '段落；區塊', tags: ['study', 'noun'] },
  { word: 'select', meaningZh: '選擇', tags: ['general', 'verb'] },
  { word: 'service', meaningZh: '服務', tags: ['business', 'noun'] },
  { word: 'share', meaningZh: '分享', tags: ['general', 'verb'] },
  { word: 'solution', meaningZh: '解法', tags: ['work', 'noun'] },
  { word: 'source', meaningZh: '來源', tags: ['study', 'noun'] },
  { word: 'specific', meaningZh: '具體的', tags: ['study', 'adjective'] },
  { word: 'strategy', meaningZh: '策略', tags: ['business', 'noun'] },
  { word: 'structure', meaningZh: '結構', tags: ['study', 'noun'] },
  { word: 'suggest', meaningZh: '建議', tags: ['general', 'verb'] },
  { word: 'support', meaningZh: '支持', tags: ['emotion', 'verb'] },
  { word: 'system', meaningZh: '系統', tags: ['technology', 'noun'] },
  { word: 'target', meaningZh: '目標', tags: ['business', 'noun'] },
  { word: 'task', meaningZh: '任務', tags: ['work', 'noun'] },
  { word: 'team', meaningZh: '團隊', tags: ['work', 'noun'] },
  { word: 'technique', meaningZh: '技巧', tags: ['study', 'noun'] },
  { word: 'temporary', meaningZh: '暫時的', tags: ['general', 'adjective'] },
  { word: 'topic', meaningZh: '主題', tags: ['language', 'noun'] },
  { word: 'translate', meaningZh: '翻譯', tags: ['language', 'verb'] },
  { word: 'travel', meaningZh: '旅行', tags: ['travel', 'verb'] },
  { word: 'update', meaningZh: '更新', tags: ['technology', 'verb'] },
  { word: 'useful', meaningZh: '有用的', tags: ['general', 'adjective'] },
  { word: 'value', meaningZh: '價值', tags: ['business', 'noun'] },
  { word: 'various', meaningZh: '各種的', tags: ['general', 'adjective'] },
  { word: 'version', meaningZh: '版本', tags: ['technology', 'noun'] },
  { word: 'visual', meaningZh: '視覺的', tags: ['study', 'adjective'] },
  { word: 'volume', meaningZh: '音量；數量', tags: ['general', 'noun'] },
  { word: 'wait', meaningZh: '等待', tags: ['general', 'verb'] },
  { word: 'warning', meaningZh: '警告', tags: ['general', 'noun'] },
  { word: 'weekly', meaningZh: '每週的', tags: ['life', 'adjective'] },
  { word: 'welcome', meaningZh: '歡迎', tags: ['general', 'verb'] },
  { word: 'workflow', meaningZh: '工作流程', tags: ['work', 'noun'] },
  { word: 'workshop', meaningZh: '工作坊', tags: ['study', 'noun'] }
]

const TIME_PARTS = [
  { ja: '毎朝', zh: '每天早上' },
  { ja: '毎晩', zh: '每天晚上' },
  { ja: '週末に', zh: '在週末' },
  { ja: '昼休みに', zh: '在午休時' },
  { ja: '通勤中に', zh: '在通勤途中' },
  { ja: '寝る前に', zh: '在睡前' },
  { ja: '授業の前に', zh: '在上課前' },
  { ja: '仕事の後で', zh: '在下班後' },
  { ja: '休みの日に', zh: '在休假日' },
  { ja: '朝の時間に', zh: '在早晨時段' }
] as const

const PLACE_PARTS = [
  { ja: '家で', zh: '在家裡', tag: 'home' },
  { ja: '図書館で', zh: '在圖書館', tag: 'library' },
  { ja: 'カフェで', zh: '在咖啡廳', tag: 'cafe' },
  { ja: '会社で', zh: '在公司', tag: 'work' },
  { ja: '学校で', zh: '在學校', tag: 'school' },
  { ja: '電車で', zh: '在電車上', tag: 'commute' },
  { ja: '公園で', zh: '在公園', tag: 'outdoor' },
  { ja: 'オンラインで', zh: '在線上', tag: 'online' }
] as const

const ACTION_PARTS = [
  { ja: '日本語の単語を復習します。', zh: '複習日文單字。', tag: 'vocabulary' },
  { ja: '新しい文法を練習します。', zh: '練習新的文法。', tag: 'grammar' },
  { ja: 'ニュース記事を読みます。', zh: '閱讀新聞文章。', tag: 'news' },
  { ja: '例文を声に出して読みます。', zh: '把例句大聲朗讀。', tag: 'speaking' },
  { ja: '会話の練習をします。', zh: '進行會話練習。', tag: 'conversation' },
  { ja: '短い日記を書きます。', zh: '寫短篇日記。', tag: 'writing' },
  { ja: '発音をチェックします。', zh: '檢查發音。', tag: 'pronunciation' },
  { ja: 'ポッドキャストを聞きます。', zh: '收聽 Podcast。', tag: 'listening' },
  { ja: '字幕つきの動画を見ます。', zh: '看有字幕的影片。', tag: 'video' },
  { ja: 'アプリでクイズを解きます。', zh: '在 App 裡做測驗。', tag: 'quiz' },
  { ja: '先生に質問します。', zh: '向老師提問。', tag: 'question' },
  { ja: '単語カードを作ります。', zh: '製作單字卡。', tag: 'flashcard' }
] as const

export function generateEnglishSeedWords(count = 240): SeedEnglishWord[] {
  return ENGLISH_SEED_BASE.slice(0, count)
}

export function generateJapaneseSeedSentences(count = 240): SeedJapaneseSentence[] {
  const items: SeedJapaneseSentence[] = []

  for (const time of TIME_PARTS) {
    for (const place of PLACE_PARTS) {
      for (const action of ACTION_PARTS) {
        const sentence = `${time.ja}${place.ja}${action.ja}`
        items.push({
          sentence,
          romaji: toRomaji(sentence),
          meaningZh: `${time.zh}${place.zh}${action.zh}`,
          vocabulary: [
            { word: '単語', meaningZh: '單字' },
            { word: '練習', meaningZh: '練習' }
          ],
          tags: ['daily', place.tag, action.tag]
        })

        if (items.length >= count) {
          return items
        }
      }
    }
  }

  return items
}
